-- AIR Research — Oracle 23c Free スキーマ初期化
-- gvenzl/oracle-free の /container-entrypoint-initdb.d/ に配置すると自動実行

-- アプリケーションユーザー作成
ALTER SESSION SET CONTAINER = FREEPDB1;

CREATE USER air_app IDENTIFIED BY air_pass
  DEFAULT TABLESPACE USERS
  QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE, CREATE VIEW TO air_app;

-- 以降は air_app スキーマで実行
ALTER SESSION SET CURRENT_SCHEMA = air_app;

-- ================================================================
-- コアテーブル
-- ================================================================

CREATE TABLE buildings (
    building_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR2(100) NOT NULL,
    address     VARCHAR2(200),
    built_year  NUMBER(4),
    structure   VARCHAR2(20)
);

CREATE TABLE rooms (
    room_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    building_id    NUMBER NOT NULL REFERENCES buildings(building_id),
    name           VARCHAR2(50) NOT NULL,
    floor          NUMBER,
    area_m2        NUMBER(6,1),
    window_count   NUMBER DEFAULT 0,
    occupancy_max  NUMBER,
    renovation_year NUMBER(4),
    notes          VARCHAR2(200)
);

CREATE TABLE sensors (
    sensor_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id      NUMBER NOT NULL REFERENCES rooms(room_id),
    model        VARCHAR2(50) NOT NULL,
    firmware_ver VARCHAR2(20),
    installed_at DATE DEFAULT SYSDATE,
    status       VARCHAR2(10) DEFAULT 'active'
);

CREATE TABLE sensor_readings (
    reading_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sensor_id      NUMBER NOT NULL REFERENCES sensors(sensor_id),
    room_id        NUMBER NOT NULL REFERENCES rooms(room_id),
    recorded_at    DATE NOT NULL,
    temperature    NUMBER(4,1),
    humidity       NUMBER(4,1),
    iaq_score      NUMBER(4),
    voc_ppm        NUMBER(6,1),
    co2_ppm        NUMBER(5),
    airflow_idx    NUMBER(3,1),
    comfort_index  NUMBER(3,1),
    CONSTRAINT pk_reading_time UNIQUE (sensor_id, recorded_at)
);

CREATE INDEX idx_readings_room_time
    ON sensor_readings(room_id, recorded_at DESC);

CREATE INDEX idx_readings_comfort
    ON sensor_readings(comfort_index)
    WHERE comfort_index < 30;

-- ================================================================
-- 設計フィードバックテーブル
-- ================================================================

CREATE TABLE complaints (
    complaint_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id         NUMBER NOT NULL REFERENCES rooms(room_id),
    client_name     VARCHAR2(50),
    reported_at     DATE DEFAULT SYSDATE,
    symptom_type    VARCHAR2(30),
    description     VARCHAR2(500),
    severity        NUMBER(1) CHECK (severity BETWEEN 1 AND 5),
    resolved        CHAR(1) DEFAULT 'N' CHECK (resolved IN ('Y','N')),
    resolution_note VARCHAR2(500),
    resolved_at     DATE
);

CREATE TABLE design_specs (
    spec_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id            NUMBER NOT NULL REFERENCES rooms(room_id),
    spec_iaq_target    NUMBER(3) DEFAULT 50,
    spec_temp_min      NUMBER(3,1) DEFAULT 22,
    spec_temp_max      NUMBER(3,1) DEFAULT 26,
    spec_humidity_min  NUMBER(3,1) DEFAULT 40,
    spec_humidity_max  NUMBER(3,1) DEFAULT 60,
    airflow_design_cfm NUMBER(6,1),
    updated_at         DATE DEFAULT SYSDATE,
    updated_by         VARCHAR2(50)
);

CREATE TABLE material_emissions (
    material_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id           NUMBER NOT NULL REFERENCES rooms(room_id),
    material_name     VARCHAR2(100),
    category          VARCHAR2(30),
    voc_emission_rate NUMBER(6,2),
    formaldehyde_ppm  NUMBER(5,3),
    certification     VARCHAR2(50),
    installed_at      DATE
);

-- ================================================================
-- 環境補助データ
-- ================================================================

CREATE TABLE weather_data (
    weather_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recorded_at      DATE NOT NULL,
    outdoor_temp     NUMBER(4,1),
    outdoor_humidity NUMBER(4,1),
    wind_speed       NUMBER(4,1),
    pressure         NUMBER(5,1),
    weather_code     VARCHAR2(20)
);

CREATE TABLE occupancy_log (
    log_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id      NUMBER NOT NULL REFERENCES rooms(room_id),
    start_at     DATE NOT NULL,
    end_at       DATE,
    person_count NUMBER,
    source       VARCHAR2(20) DEFAULT 'manual'
);

-- ================================================================
-- ビュー
-- ================================================================

CREATE OR REPLACE VIEW v_room_comfort_summary AS
SELECT
    r.room_id,
    r.name,
    ROUND(AVG(sr.temperature), 1)           AS avg_temp,
    ROUND(AVG(sr.humidity), 1)              AS avg_humidity,
    ROUND(AVG(sr.iaq_score))                AS avg_iaq,
    ROUND(AVG(sr.comfort_index), 1)         AS avg_comfort,
    COUNT(c.complaint_id)                   AS complaint_count,
    MAX(sr.recorded_at)                     AS last_reading
FROM rooms r
LEFT JOIN sensor_readings sr ON r.room_id = sr.room_id
LEFT JOIN complaints c ON r.room_id = c.room_id AND c.resolved = 'N'
GROUP BY r.room_id, r.name;

CREATE OR REPLACE VIEW v_iaq_vs_complaints AS
SELECT
    TRUNC(sr.recorded_at, 'HH')             AS hour_slot,
    r.room_id,
    r.name,
    ROUND(AVG(sr.iaq_score))                AS avg_iaq,
    ROUND(AVG(sr.comfort_index), 1)         AS avg_comfort,
    COUNT(c.complaint_id)                   AS complaints
FROM rooms r
JOIN sensor_readings sr ON r.room_id = sr.room_id
LEFT JOIN complaints c ON r.room_id = c.room_id
    AND TRUNC(c.reported_at, 'HH') = TRUNC(sr.recorded_at, 'HH')
GROUP BY TRUNC(sr.recorded_at, 'HH'), r.room_id, r.name;

-- ================================================================
-- サンプルデータ
-- ================================================================

INSERT INTO buildings (name, address, built_year, structure) VALUES
    ('霞が関ビル', '東京都千代田区霞が関1-1', 1968, 'S');

INSERT INTO rooms (building_id, name, floor, area_m2, window_count, occupancy_max, renovation_year) VALUES
    (1, '会議室A', 8, 40.5, 2, 12, 2020);
INSERT INTO rooms (building_id, name, floor, area_m2, window_count, occupancy_max, renovation_year) VALUES
    (1, 'オープンラウンジ', 1, 120.0, 6, 40, 2018);

INSERT INTO sensors (room_id, model, firmware_ver) VALUES
    (1, 'BME680', 'v2.1.0');
INSERT INTO sensors (room_id, model, firmware_ver) VALUES
    (2, 'BME680', 'v2.1.0');

INSERT INTO sensor_readings (sensor_id, room_id, recorded_at, temperature, humidity, iaq_score, voc_ppm, co2_ppm, airflow_idx, comfort_index)
SELECT 1, 1,
    TO_DATE('2026-06-23 '||LPAD(LEVEL+8,2,'0')||':00:00', 'YYYY-MM-DD HH24:MI:SS'),
    ROUND(DBMS_RANDOM.VALUE(23, 28), 1),
    ROUND(DBMS_RANDOM.VALUE(30, 55), 1),
    ROUND(DBMS_RANDOM.VALUE(30, 120)),
    ROUND(DBMS_RANDOM.VALUE(0.1, 2.0), 1),
    ROUND(DBMS_RANDOM.VALUE(400, 1200)),
    ROUND(DBMS_RANDOM.VALUE(0.1, 3.0), 1),
    ROUND(DBMS_RANDOM.VALUE(20, 80), 1)
FROM DUAL CONNECT BY LEVEL <= 9;

INSERT INTO sensor_readings (sensor_id, room_id, recorded_at, temperature, humidity, iaq_score, voc_ppm, co2_ppm, airflow_idx, comfort_index)
SELECT 2, 2,
    TO_DATE('2026-06-23 '||LPAD(LEVEL+8,2,'0')||':00:00', 'YYYY-MM-DD HH24:MI:SS'),
    ROUND(DBMS_RANDOM.VALUE(24, 30), 1),
    ROUND(DBMS_RANDOM.VALUE(35, 60), 1),
    ROUND(DBMS_RANDOM.VALUE(40, 150)),
    ROUND(DBMS_RANDOM.VALUE(0.2, 2.5), 1),
    ROUND(DBMS_RANDOM.VALUE(450, 1300)),
    ROUND(DBMS_RANDOM.VALUE(0.2, 4.0), 1),
    ROUND(DBMS_RANDOM.VALUE(15, 75), 1)
FROM DUAL CONNECT BY LEVEL <= 9;

INSERT INTO complaints (room_id, client_name, reported_at, symptom_type, description, severity) VALUES
    (1, '佐藤部長', TO_DATE('2026-06-23 14:30', 'YYYY-MM-DD HH24:MI'), '眠気',
     '午後の会議でいつも眠くなる。換気が悪いんじゃないか', 3);
INSERT INTO complaints (room_id, client_name, reported_at, symptom_type, description, severity) VALUES
    (2, '田中(総務)', TO_DATE('2026-06-20 10:15', 'YYYY-MM-DD HH24:MI'), '臭気',
     'ラウンジに何か化学的な匂いがある。新しく置いた観葉植物の土？', 2);

COMMIT;
